Kan 65 sportplatz anträge im backend implementieren
OlympGuide/Backend pull request #15
Opened 2024-04-16 18:03 UTC by Ilimea

Entity für Sportfeld Antrag
Controller
Service
Repository
Event
Eventhandler

→ Mediator Pattern verwenden

2024-04-16 18:26 UTC, SuffPanda commented on OlympGuide.Application/Features/SportFieldProposal/SportFieldProposalService.cs
> +                var Event = new SportFieldProposalAcceptedEvent(sportFieldProposal);
lowercase

2024-04-16 18:39 UTC, SuffPanda commented on OlympGuide/Controllers/SportFieldProposalController.cs
> +            if (state.Equals(SportFieldProposalStates.Open))
rewrite to if open then getAllOpen... else getAll..

2024-04-17 11:01 UTC, mueld requested changes

2024-04-17 11:01 UTC, mueld commented on OlympGuide.Application/Features/SportField/SportFieldValidation.cs
> +namespace OlympGuide.Application.Features.SportField
As this class validates a domain entity, it should be moved to the domain layer. It contains specific domain logic.
Don't forget to adapt the namespace when you move the file!

2024-04-17 11:01 UTC, mueld commented on OlympGuide.Application/Features/SportFieldProposal/ISportFieldProposalService.cs
> +}
Interface belongs to the domain layer

2024-04-17 11:01 UTC, mueld commented on OlympGuide.Application/Features/SportFieldProposal/NoSportFieldProposalFoundException.cs
> +}
belongs to the domain layer

2024-04-17 11:01 UTC, mueld commented on OlympGuide.Application/Features/SportFieldProposal/SportFieldProposalApprovedEvent.cs
> +}
move to domain layer

2024-04-17 11:01 UTC, mueld commented on OlympGuide.Infrastructre/Repositories/SportFieldProposalRepository.cs
> +            return sportFieldProposalList;
`return  await context.SportFieldProposals .ToListAsync();`

2024-04-17 11:01 UTC, mueld commented on OlympGuide.Infrastructre/Repositories/SportFieldProposalRepository.cs
> +            return sportFieldProposalList;
same

2024-04-17 11:01 UTC, mueld commented on OlympGuide.Infrastructre/Repositories/SportFieldProposalRepository.cs
> +            return sportFieldProposal;
same

2024-04-17 11:20 UTC, Ilimea commented on OlympGuide.Application/Features/SportFieldProposal/ISportFieldProposalService.cs
> +}
nach Absprache in Application gelassen

2024-04-17 13:10 UTC, mueld approved these changes

2024-04-17 13:12 UTC, merged